version: '3'
name: 'report-builder'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reports
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - '5444:5432'
    networks:
      - app-network

networks:
  app-network:
